
# auto-generated by configure
PREFIX = /usr/local
VERSION = 2.12.3
CC = gcc
CFLAGS = -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -mmacosx-version-min=10.7 -I./lib -I/opt/X11/include/libpng16  -I/usr/local/Cellar/little-cms2/2.9/include -DUSE_LCMS=1
LDFLAGS =  -mmacosx-version-min=10.7 ./lib/libimagequant.a -L/opt/X11/lib -lpng16 -lz -L/usr/local/Cellar/little-cms2/2.9/lib -llcms2 -lm
SOLIBSUFFIX = dylib
STATICLIBDEPS = ./lib/libimagequant.h ./lib/libimagequant.a
LIQSRCDIR = ./lib
LIQCONFIGUREFLAGS = '--quiet' 

